name: Build and Push Docker Images

on:
  schedule:
    - cron: '0 19 * * 5' # At 19:00 on Friday UTC (AEST 5:00 Saturday)
  workflow_dispatch:

jobs:
  build_and_push_tdarr_base:
    name: Build and Push tdarr_base
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract date for tag
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Build and push tdarr_base Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/tdarr_base
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tdarr_base:noble_${{ steps.date.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tdarr_base:latest

  build_and_push_tdarr_server:
    name: Build and Push tdarr_server
    runs-on: ubuntu-latest
    needs: build_and_push_tdarr_base
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tdarr_base Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/tdarr/Dockerfile
          push: true
          build-args: |
            VERSION=2.58.02
            MODULE=Tdarr_Server
            DATE=${{ needs.build_and_push_tdarr_base.outputs.date }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tdarr:noble_${{ needs.build_and_push_tdarr_base.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tdarr:latest